# Generated by Django 4.1.6 on 2023-02-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.IntegerField()),
                ('publisher', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('cover', models.ImageField(blank=True, upload_to='covers/')),
                ('summary', models.TextField(default="It's a game", max_length=350)),
                ('genre', models.CharField(choices=[(None, '(Unknown)'), ('Action', 'Act'), ('Suspense', 'Sus'), ('Puzzle', 'Puz'), ('Mistery', 'Mis'), ('Adventury', 'Adv')], max_length=9)),
            ],
            options={
                'db_table': 'Games',
            },
        ),
    ]
